# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdc034c136d7c3ee7bff1951c3cd0e78399a765994b7562e800d1343557aec796d7debd72f9911db5f5a2066d7fbd6810655faf0bc67988832c8438293d2992c

test:
  secret_key_base: 4a1f61849c93a62f7db8bab0ebf5ddc178e111f9b9c84c8f5a034eca075ebb995702d3577e484523be7093ae038fb63c90d28fe8e53536b1c0c3be3cfd3b6be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4a1f61849c93a62f7db8bab0ebf5ddc178e111f9b9c84c8f5a034eca075ebb995702d3577e484523be7093ae038fb63c90d28fe8e53536b1c0c3be3cfd3b6be3
  secret_token: 24ff6234908h3489gfn8s0e00sd9hfm023094nfnm2390nf092390hjf0sjndfosdoihcvc;zklshdvli87shgh4ektbszdlkf7g4wjktgbwail7f45gc90d2lkjjhg0